export const campaigns = [
  {
    title: "Google",
    img: "/assets/googlecampaign.png",
    url: "https://google.com",
    campaignName: "Google ads",
    ads: "New ads",
  },
  {
    title: "Facebook",
    img: "/assets/fbcampaign.png",
    url: "https://google.com",
    campaignName: "Facebook ads",
    ads: "New ads",
  },
  {
    title: "Instagram",
    img: "/assets/instacampaign.png",
    url: "https://google.com",
    campaignName: "Instagram ads",
    ads: "New ads",
  },
  {
    title: "Youtube",
    img: "/assets/youtubecampaign.png",
    url: "https://google.com",
    campaignName: "Youtube ads",
    ads: "New ads",
  },
  {
    title: "Google",
    img: "/assets/googlecampaign.png",
    url: "https://google.com",
    campaignName: "Google ads",
    ads: "New ads",
  },
  {
    title: "Facebook",
    img: "/assets/fbcampaign.png",
    url: "https://google.com",
    campaignName: "Facebook ads",
    ads: "New ads",
  },
  {
    title: "Instagram",
    img: "/assets/instacampaign.png",
    url: "https://google.com",
    campaignName: "Instagram ads",
    ads: "New ads",
  },
  {
    title: "Youtube",
    img: "/assets/youtubecampaign.png",
    url: "https://google.com",
    campaignName: "Youtube ads",
    ads: "New ads",
  },
];

export const facebookOptimizationGoalOptions = [
  { value: "NONE", label: "None" },
  { value: "APP_INSTALLS", label: "App Installs" },
  { value: "AD_RECALL_LIFT", label: "Ad Recall Lift" },
  { value: "ENGAGED_USERS", label: "Engaged Users" },
  { value: "EVENT_RESPONSES", label: "Event Responses" },
  { value: "IMPRESSIONS", label: "Impressions" },
  { value: "LEAD_GENERATION", label: "Lead Generation" },
  { value: "QUALITY_LEAD", label: "Quality Lead" },
  { value: "LINK_CLICKS", label: "Link Clicks" },
  { value: "OFFSITE_CONVERSIONS", label: "Offsite Conversions" },
  { value: "PAGE_LIKES", label: "Page Likes" },
  { value: "POST_ENGAGEMENT", label: "Post Engagement" },
  { value: "QUALITY_CALL", label: "Quality Call" },
  { value: "REACH", label: "Reach" },
  { value: "LANDING_PAGE_VIEWS", label: "Landing Page Views" },
  { value: "VISIT_INSTAGRAM_PROFILE", label: "Visit Instagram Profile" },
  { value: "VALUE", label: "Value" },
  { value: "THRUPLAY", label: "ThruPlay" },
  { value: "DERIVED_EVENTS", label: "Derived Events" },
  {
    value: "APP_INSTALLS_AND_OFFSITE_CONVERSIONS",
    label: "App Installs and Offsite Conversions",
  },
  { value: "CONVERSATIONS", label: "Conversations" },
  { value: "IN_APP_VALUE", label: "In-App Value" },
  {
    value: "MESSAGING_PURCHASE_CONVERSION",
    label: "Messaging Purchase Conversion",
  },
  { value: "SUBSCRIBERS", label: "Subscribers" },
  { value: "REMINDERS_SET", label: "Reminders Set" },
  { value: "MEANINGFUL_CALL_ATTEMPT", label: "Meaningful Call Attempt" },
  { value: "PROFILE_VISIT", label: "Profile Visit" },
  {
    value: "MESSAGING_APPOINTMENT_CONVERSION",
    label: "Messaging Appointment Conversion",
  },
];

export const countries: any = [
  { label: "Afghanistan", value: "afghanistan" },
  { label: "Albania", value: "albania" },
  { label: "Algeria", value: "algeria" },
  { label: "Andorra", value: "andorra" },
  { label: "Angola", value: "angola" },
  { label: "Antigua and Barbuda", value: "antigua-and-barbuda" },
  { label: "Argentina", value: "argentina" },
  { label: "Armenia", value: "armenia" },
  { label: "Australia", value: "australia" },
  { label: "Austria", value: "austria" },
  { label: "Azerbaijan", value: "azerbaijan" },
  { label: "Bahamas", value: "bahamas" },
  { label: "Bahrain", value: "bahrain" },
  { label: "Bangladesh", value: "bangladesh" },
  { label: "Barbados", value: "barbados" },
  { label: "Belarus", value: "belarus" },
  { label: "Belgium", value: "belgium" },
  { label: "Belize", value: "belize" },
  { label: "Benin", value: "benin" },
  { label: "Bhutan", value: "bhutan" },
  { label: "Bolivia", value: "bolivia" },
  { label: "Bosnia and Herzegovina", value: "bosnia-and-herzegovina" },
  { label: "Botswana", value: "botswana" },
  { label: "Brazil", value: "brazil" },
  { label: "Brunei", value: "brunei" },
  { label: "Bulgaria", value: "bulgaria" },
  { label: "Burkina Faso", value: "burkina-faso" },
  { label: "Burundi", value: "burundi" },
  { label: "Cabo Verde", value: "cabo-verde" },
  { label: "Cambodia", value: "cambodia" },
  { label: "Cameroon", value: "cameroon" },
  { label: "Canada", value: "canada" },
  { label: "Central African Republic", value: "central-african-republic" },
  { label: "Chad", value: "chad" },
  { label: "Chile", value: "chile" },
  { label: "China", value: "china" },
  { label: "Colombia", value: "colombia" },
  { label: "Comoros", value: "comoros" },
  { label: "Congo (Congo-Brazzaville)", value: "congo-brazzaville" },
  { label: "Costa Rica", value: "costa-rica" },
  { label: "Croatia", value: "croatia" },
  { label: "Cuba", value: "cuba" },
  { label: "Cyprus", value: "cyprus" },
  { label: "Czechia (Czech Republic)", value: "czechia" },
  { label: "Denmark", value: "denmark" },
  { label: "Djibouti", value: "djibouti" },
  { label: "Dominica", value: "dominica" },
  { label: "Dominican Republic", value: "dominican-republic" },
  { label: "Ecuador", value: "ecuador" },
  { label: "Egypt", value: "egypt" },
  { label: "El Salvador", value: "el-salvador" },
  { label: "Equatorial Guinea", value: "equatorial-guinea" },
  { label: "Eritrea", value: "eritrea" },
  { label: "Estonia", value: "estonia" },
  { label: "Eswatini", value: "eswatini" },
  { label: "Ethiopia", value: "ethiopia" },
  { label: "Fiji", value: "fiji" },
  { label: "Finland", value: "finland" },
  { label: "France", value: "france" },
  { label: "Gabon", value: "gabon" },
  { label: "Gambia", value: "gambia" },
  { label: "Georgia", value: "georgia" },
  { label: "Germany", value: "germany" },
  { label: "Ghana", value: "ghana" },
  { label: "Greece", value: "greece" },
  { label: "Grenada", value: "grenada" },
  { label: "Guatemala", value: "guatemala" },
  { label: "Guinea", value: "guinea" },
  { label: "Guinea-Bissau", value: "guinea-bissau" },
  { label: "Guyana", value: "guyana" },
  { label: "Haiti", value: "haiti" },
  { label: "Holy See", value: "holy-see" },
  { label: "Honduras", value: "honduras" },
  { label: "Hungary", value: "hungary" },
  { label: "Iceland", value: "iceland" },
  { label: "India", value: "india" },
  { label: "Indonesia", value: "indonesia" },
  { label: "Iran", value: "iran" },
  { label: "Iraq", value: "iraq" },
  { label: "Ireland", value: "ireland" },
  { label: "Israel", value: "israel" },
  { label: "Italy", value: "italy" },
  { label: "Jamaica", value: "jamaica" },
  { label: "Japan", value: "japan" },
  { label: "Jordan", value: "jordan" },
  { label: "Kazakhstan", value: "kazakhstan" },
  { label: "Kenya", value: "kenya" },
  { label: "Kiribati", value: "kiribati" },
  { label: "Korea (North)", value: "north-korea" },
  { label: "Korea (South)", value: "south-korea" },
  { label: "Kosovo", value: "kosovo" },
  { label: "Kuwait", value: "kuwait" },
  { label: "Kyrgyzstan", value: "kyrgyzstan" },
  { label: "Laos", value: "laos" },
  { label: "Latvia", value: "latvia" },
  { label: "Lebanon", value: "lebanon" },
  { label: "Lesotho", value: "lesotho" },
  { label: "Liberia", value: "liberia" },
  { label: "Libya", value: "libya" },
  { label: "Liechtenstein", value: "liechtenstein" },
  { label: "Lithuania", value: "lithuania" },
  { label: "Luxembourg", value: "luxembourg" },
  { label: "Madagascar", value: "madagascar" },
  { label: "Malawi", value: "malawi" },
  { label: "Malaysia", value: "malaysia" },
  { label: "Maldives", value: "maldives" },
  { label: "Mali", value: "mali" },
  { label: "Malta", value: "malta" },
  { label: "Marshall Islands", value: "marshall-islands" },
  { label: "Mauritania", value: "mauritania" },
  { label: "Mauritius", value: "mauritius" },
  { label: "Mexico", value: "mexico" },
  { label: "Micronesia", value: "micronesia" },
  { label: "Moldova", value: "moldova" },
  { label: "Monaco", value: "monaco" },
  { label: "Mongolia", value: "mongolia" },
  { label: "Montenegro", value: "montenegro" },
  { label: "Morocco", value: "morocco" },
  { label: "Mozambique", value: "mozambique" },
  { label: "Myanmar", value: "myanmar" },
  { label: "Namibia", value: "namibia" },
  { label: "Nauru", value: "nauru" },
  { label: "Nepal", value: "nepal" },
  { label: "Netherlands", value: "netherlands" },
  { label: "New Zealand", value: "new-zealand" },
  { label: "Nicaragua", value: "nicaragua" },
  { label: "Niger", value: "niger" },
  { label: "Nigeria", value: "nigeria" },
  { label: "North Macedonia", value: "north-macedonia" },
  { label: "Norway", value: "norway" },
  { label: "Oman", value: "oman" },
  { label: "Pakistan", value: "pakistan" },
  { label: "Palau", value: "palau" },
  { label: "Panama", value: "panama" },
  { label: "Papua New Guinea", value: "papua-new-guinea" },
  { label: "Paraguay", value: "paraguay" },
  { label: "Peru", value: "peru" },
  { label: "Philippines", value: "philippines" },
  { label: "Poland", value: "poland" },
  { label: "Portugal", value: "portugal" },
  { label: "Qatar", value: "qatar" },
  { label: "Romania", value: "romania" },
  { label: "Russia", value: "russia" },
  { label: "Rwanda", value: "rwanda" },
  { label: "Saint Kitts and Nevis", value: "saint-kitts-and-nevis" },
  { label: "Saint Lucia", value: "saint-lucia" },
  {
    label: "Saint Vincent and the Grenadines",
    value: "saint-vincent-and-the-grenadines",
  },
  { label: "Samoa", value: "samoa" },
  { label: "San Marino", value: "san-marino" },
  { label: "Sao Tome and Principe", value: "sao-tome-and-principe" },
  { label: "Saudi Arabia", value: "saudi-arabia" },
  { label: "Senegal", value: "senegal" },
  { label: "Serbia", value: "serbia" },
  { label: "Seychelles", value: "seychelles" },
  { label: "Sierra Leone", value: "sierra-leone" },
  { label: "Singapore", value: "singapore" },
  { label: "Slovakia", value: "slovakia" },
  { label: "Slovenia", value: "slovenia" },
  { label: "Solomon Islands", value: "solomon-islands" },
  { label: "Somalia", value: "somalia" },
  { label: "South Africa", value: "south-africa" },
  { label: "South Sudan", value: "south-sudan" },
  { label: "Spain", value: "spain" },
  { label: "Sri Lanka", value: "sri-lanka" },
  { label: "Sudan", value: "sudan" },
  { label: "Suriname", value: "suriname" },
  { label: "Sweden", value: "sweden" },
  { label: "Switzerland", value: "switzerland" },
  { label: "Syria", value: "syria" },
  { label: "Taiwan", value: "taiwan" },
  { label: "Tajikistan", value: "tajikistan" },
  { label: "Tanzania", value: "tanzania" },
  { label: "Thailand", value: "thailand" },
  { label: "Timor-Leste", value: "timor-leste" },
  { label: "Togo", value: "togo" },
  { label: "Tonga", value: "tonga" },
  { label: "Trinidad and Tobago", value: "trinidad-and-tobago" },
  { label: "Tunisia", value: "tunisia" },
  { label: "Turkey", value: "turkey" },
  { label: "Turkmenistan", value: "turkmenistan" },
  { label: "Tuvalu", value: "tuvalu" },
  { label: "Uganda", value: "uganda" },
  { label: "Ukraine", value: "ukraine" },
  { label: "United Arab Emirates", value: "united-arab-emirates" },
  { label: "United Kingdom", value: "united-kingdom" },
  { label: "United States", value: "united-states" },
  { label: "Uruguay", value: "uruguay" },
  { label: "Uzbekistan", value: "uzbekistan" },
  { label: "Vanuatu", value: "vanuatu" },
  { label: "Venezuela", value: "venezuela" },
  { label: "Vietnam", value: "vietnam" },
  { label: "Yemen", value: "yemen" },
  { label: "Zambia", value: "zambia" },
  { label: "Zimbabwe", value: "zimbabwe" },
];
